### PR TITLE
Add SMD pot footprints

### PR DESCRIPTION
**Pull request by evanshultz**
The SMD pot footprints. After removing the reverse mount ones and adding variants with a hole, we're left with 7. I chose a `_Hole` suffix and, of course, 3D models will (or may) be broken because of name changes.

These incorporate the changes mentioned here:
- https://github.com/KiCad/Potentiometers.pretty/issues/18
- https://github.com/KiCad/Potentiometers.pretty/issues/20

If these are all good, I'll finish up the script similarly for THT pot footprints and upload them.

Image:
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Hang on. The description and 3D model params aren't being set properly.

**Comment by evanshultz** [comment]
3D model params were easy to fix, but I will have to work more on the description/tag weirdness tomorrow. Any suggestions on footprint naming? `Potentiometer_[P[X][xY][xZ]|MPN]_P[Pitch X][xPitch Y]_[Vertical|Horizontal][_Options]`?

**Comment by evanshultz** [comment]
Check out the updated footprints and please provide feedback. I do not think this is ready to merge yet.

Changes:
- Fixed descriptions
- Fixed 3D model params (scaling)
- Remove silk circle for shaft under part

I have found some small errors in the pad sizes, dimensions, etc., but I assume it's best to get footprints into the library (unchanged from the old ones in these respects). In some cases the script does not support correcting the errors so adding functionality (or just re-writing) the script is best done later.

**Comment by evanshultz** [comment]
Sorry that I've been out. I have a brain tumor that slowed me down and will reduce my ability to help for a couple more weeks.

I ended up having to tweak the PRS11S by hand due to limitations in the script to make it work, but otherwise here are all the SMD potentiometer footprints and I believe they're all correct now:
image

Script/footprint issues are noted at https://github.com/KiCad/kicad-footprints/issues/188.

This is ready for review and merge!

**Comment by evanshultz** [comment]
@SchrodingersGat Why isn't Travis checking this PR?

**Comment by evanshultz** [comment]
FYI, since these footprints are all unique they ended up as `Potentiometer_Mfr_MPN_[Vertical|Horizontal][_Hole]`.

**Comment by evanshultz** [comment]
Oops. There were more. Here are the rest of the SMD pots:
image

**Comment by evanshultz** [comment]
And here are the THT footprints. No screenshot because there are so many but a cursory check seems to have fixed the major pot footprint issues noted before (and again above).

**Comment by evanshultz** [comment]
And here are the notes that I've kept as I made changes to the script:
```
- Separated SMD and THT generation scripts in accordance with library repo names
- Fixed Horizontal/Vertical confusion [https://github.com/KiCad/Potentiometers.pretty/issues/18]
- Updated footprint names to match KLC 3
- Force float division for Python 2.7 compatibility (`/2.0` instead of `/2`)
- Add F.Fab refdes [https://github.com/KiCad/Potentiometers.pretty/issues/20]
- Generated Bourns 3009P (all param info was there but no call to generate footprint function)
- Do not generate THT footprints with a hole if the datasheet doesn't show leads prepped appropriately
- Many fixes or updates to footprint names for clarity
- Changed silk offset to 0.12mm (now totally outside of SMT parts)
- Added env var to 3D model path
- Removed pin number from mounting holes
- Remove `print(hbody,pinyoffset)` for Bourns 3006Y/W
- Remove pin number for through-board mounting holes
- Remove unusd `pn` variable
- Declare and assign values to slk_offset and txt_offset variables
- Add argument interface to footprint_scripts_potentiometers.py
- Greatly simplified generating footprint name, description, and tags
- Removed required "classname" and "footprint_name" parameters
- Changed "deco" parameter to "screwstyle" for vertical pots
- Changed "mount_below" parameter to "shaft_hole" function and default to False
- Changed name_additions behavior to accept a list of strings
- Changed "Double" in footprint name to "Dual"
- All footprints use proper 3D model parameters
- Add function headers to footprint_scripts_potentiometers.py
- Add additional commenting to all files (still underdocumented)

Beware: There is little to no error checking in the code. Also, there are a number of variable names that I find obscure and possibly more unused variables. Major refactoring could improve this code. And the way the name_additions works by splitting up a text string is weird. But I think this is OK for now.

Also note that I didn't check each and every dimension!
```

Let me know if you find anything wrong hopefully this is ready to merge or very close so the lib is complete. The only major omission is https://github.com/KiCad/Potentiometers.pretty/pull/23, but that doesn't have a good solution yet and I'll raise a new issue about it in the new repo once the footprints are merged.

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat Why isn't Travis checking this PR?

https://github.com/**evanshultz**/kicad-footprints/pull/3

**Pull request closed without merging**
